### PR TITLE
Add MFM floppy emulator

### PR DESCRIPTION
**Pull request by jepler**
Targeted feature list for this version
- [x] Basic flux output
- [x] read flux data from SD cards
- [x] select file from SD card
- [x] obey track changes
- [x] obey side changes
- [x] obey motor & select lines
- [x] handle density & RPM options by image file size detection

This PR will not encompass
- flux writing from computer to floppsy
- working with fm-coded data

### CODE REVIEW

**Comment by jepler** [comment]
As a milestone, greasweazle can now grok the flux produced by the USB floppy sketch.
```
$ gw read  --tracks c=0:h=0 --format ibm.1440 bad.img
*** TEST/PRE-RELEASE: 1.16.4.dev4+g5b93ade.d20240619
*** Use these tools ONLY for test and development!!
Reading c=0:h=0 revs=2
Format ibm.1440
Unknown mark 4e
Unknown mark 4e
T0.0: IBM MFM (18/18 sectors) from Raw Flux (188840 flux in 400.52ms)
Cyl-> 0
H. S: 0
0. 0: .
0. 1: .
0. 2: .
0. 3: .
0. 4: .
0. 5: .
0. 6: .
0. 7: .
0. 8: .
0. 9: .
0.10: .
0.11: .
0.12: .
0.13: .
0.14: .
0.15: .
0.16: .
0.17: .
Found 18 sectors of 18 (100%)
```
dunno what's up with the unknown markers yet.

**Comment by jepler** [comment]
Now, real data from the SD card is returned. The side number is not used/checked yet.

**Comment by jepler** [comment]
@ladyada I think I've done all we set out to do here.

**Comment by ladyada** [comment]
lovel!y!

**Pull request merged**
