### PR TITLE
WIP: Start turning the MSD demo into something usable

### PR DESCRIPTION
**Pull request by jepler**
* Use the TFT on the Floppsy to show some I/O states, track & side, a "dirty" indicator, and a throbber
* add a timeout to flux capturing waiting for the index pulse
* handle disk removal/insertion about as well as I can
* make a step towards autodetection (just defining an enum value for it)
* allow re-writing a full track even if it had errors when read
  * this still has problems related to rewriting "sector zero", because
    it is flushed immediately right now
  * this is basically a low level format

### CODE REVIEW

**Comment by jepler** [comment]
* doesn't build on non-TFT boards (anything but floppsy)

**Comment by jepler** [comment]
* not tested on 5.25" drives

**Comment by jepler** [comment]
* doesn't give R/O state to host OS

**Comment by jepler** [comment]
360KiB media is detected, but track 1 is not readable. I think it may be a 40- vs 80-track difference. I think my drive is 1.2MB rotating at 360RPM, which not only has 80 tracks but explains the 1667ns flux rate too.
```
autodetecting
flux rate 2000
flux rate 1000
flux rate 867
flux rate 1667
Detected flux rate 1667ns/bit
40/2/9 C/H/S
```

**Comment by jepler** [comment]
@ladyada this is ready for review from you. I will work in a future PR on finishing support for 5.25 drives & media.

**Comment by jepler** [comment]
| Media \\ Drive | 1200 | | 360 |
| -- | -- | -- | -- |
| 1200 | OK | not tested | N/A | N/A |
| 360 | buggy | not tested | buggy | not tested |

| Media \\ Drive | 1440 | | 720 |
| -- | -- | -- | -- |
| 1440 | OK | OK | N/A | N/A |
| 720 | OK | not tested | not tested | not tested |

360 in 1200: needs to step 2 times to move from track to track
360 in 360: unclear, media insertion never detected. may be different "ready" / "disc change" signal logic in old drives

**Review by ladyada — APPROVED** [review]

**Pull request merged**
